import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from '../../api/axios';


const initialState = {
    posts: [],
    isLoading: false,
    fetchError: null
};

export const fetchPosts = createAsyncThunk(
    'posts/fetchPosts',
    async () => {
        const response = await axios.get('getPost')
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const postSlice = createSlice({
    name: 'post',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchPosts.pending, (state) => {
                state.isLoading = true;
            })
            .addCase(fetchPosts.fulfilled, (state, action) => {
                console.log(action.payload.posts)
                state.isLoading = false;
                state.posts = action.payload.posts;
            })
            .addCase(fetchPosts.rejected, (state, action) => {
                state.isLoading = false;
                state.fetchError = action.error;
            });
    }
});

export default postSlice.reducer;